openapi: 3.0.0
servers:
  - url: https://issuer.qa.veres.app/issuers/z19mTE4x8KHRaQLgdoYwsfPnU
    description: Veres Issuer (Quality Assurance)
info:
  version: "0.0.3-unstable"
  title: VC Issuer API
  description: This is an Experimental Open API Specification for the [VC Data Model](https://www.w3.org/TR/vc-data-model/).
  license:
    name: W3C Software and Document License
    url: http://www.w3.org/Consortium/Legal/copyright-software.
  contact:
    name: GitHub Source Code
    url: https://github.com/w3c-ccg/vc-api
paths:
  /credentials/issue:
    post:
      summary: Issues a credential and returns it in the response body.
      tags:
        - Credentials
      security:
        - networkAuth: []
        - oAuth2: []
        - zCap: []
      operationId: issueCredential
      x-expectedCaller: "Issuer Coordinator"
      description: Issues a credential and returns it in the response body.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IssueCredentialRequest"
        description: Parameters for issuing the credential.
      responses:
        "201":
          description: Credential successfully issued!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IssueCredentialResponse"
        "400":
          description: >
            The request could not be processed due to one of the following reasons:
                        - The provided value of 'issuer' does not match the expected configuration.
                        - Another condition that results in a Bad Request.
  /credentials/status:
    post:
      summary: Updates the status of an issued credential
      tags:
        - Credentials
      security:
        - networkAuth: []
        - oAuth2: []
        - zCap: []
      operationId: updateCredentialStatus
      x-expectedCaller: "Issuer Service"
      description: Updates the status of an issued credential.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateCredentialStatusRequest"
        description: Parameters for updating the status of the issued credential.
      responses:
        "200":
          description: Credential status successfully updated
        "400":
          description: Bad Request
        "404":
          description: Credential not found
components:
  securitySchemes:
    $ref: "./components/SecuritySchemes.yml#/components/securitySchemes"
  schemas:
    UpdateCredentialStatusRequest:
      type: object
      required: ['credentialId', 'credentialStatus', 'status']
      additionalProperties: false
      description: Credential status information to be updated.
      properties:
        credentialId:
          type: string
          description: Identifies the credential (the identifier does not have to appear in the VC itself).
        credentialStatus:
          type: object
          description: Identifies the specific status list entry to update.
          required: ['type', 'statusPurpose']
          additionalProperties: false
          properties:
            id:
              type: string
            type:
              type: string
            statusPurpose:
              type: string
            statusListIndex:
              type: string
            statusListCredential:
              type: string
        status:
          type: boolean
          description: Specifies the new status.
        indexAllocator:
          type: string
          description: For services to use which indexes are being used/assigned to VCs.
      example:
        {
          "credentialId": "0fc754bc-fc32-46a0-aec1-a5ef385e7ea0",
          "credentialStatus": { "type": "BitstringStatusList", "statusPurpose": "revocation" },
          "status": True
        }
    IssueCredentialRequest:
      type: object
      properties:
        credential:
          $ref: "./components/Credential.yml#/components/schemas/UnsecuredCredential"
        options:
          $ref: "./components/IssueCredentialOptions.yml#/components/schemas/IssueCredentialOptions"
    IssueCredentialResponse:
      type: object
      properties:
        IssueCredentialResponse:
          $ref: "./components/VerifiableCredentialResponse.yml#/components/schemas/VerifiableCredentialResponse"
