openapi: 3.0.0
info:
  version: "0.0.3-unstable"
  title: VC Issuer API
  description: This is an Experimental Open API Specification for the [VC Data Model](https://www.w3.org/TR/vc-data-model/).
  license:
    name: W3C Software and Document License
    url: http://www.w3.org/Consortium/Legal/copyright-software.
  contact:
    name: GitHub Source Code
    url: https://github.com/w3c-ccg/vc-api
paths:
  /credentials/issue:
    post:
      summary: Issues a credential and returns it in the response body.
      tags: 
       - Credentials
      operationId: issueCredential
      description: Issues a credential and returns it in the response body.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IssueCredentialRequest"
        description: Parameters for issuing the credential.
      responses:
        "201":
          description: Credential successfully issued!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IssueCredentialResponse"
        "400":
          description: invalid input!
        "500":
          description: error!
  /credentials/status:
    post:
      summary: Updates the status of an issued credential
      tags: 
       - Credentials
      operationId: updateCredentialStatus
      description: Updates the status of an issued credential.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateCredentialStatus"
        description: Parameters for updating the status of the issued credential.
      responses:
        "200":
          description: Credential status successfully updated
        "400":
          description: Bad Request
        "404":
          description: Credential not found
        "500":
          description: Internal Server Error
components:
  schemas:
    IssueCredentialRequest:
      type: object
      properties:
        credential:
          $ref: "./components/Credential.yml#/components/schemas/Credential"
        options:
          $ref: "./components/IssueCredentialOptions.yml#/components/schemas/IssueCredentialOptions"
    IssueCredentialResponse:
      $ref: "./components/VerifiableCredential.yml#/components/schemas/VerifiableCredential"
    UpdateCredentialStatus:
      type: object
      description: Request for updating the status of an issued credential.
      properties:
        credentialId:
          type: string
        credentialStatus:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
              status:
                type: string
      example:
        {
          "credentialId": "urn:uuid:45a44711-e457-4fa8-9b89-69fe0287c86a",
          "credentialStatus":
            [{ "type": "RevocationList2020Status", "status": "0" }],
        }
