openapi: 3.0.0
info:
  version: "0.0.3-unstable"
  title: VC Workflow HTTP API
  description: This is an Experimental Open API Specification for the [VC Data Model](https://www.w3.org/TR/vc-data-model/).
  license:
    name: W3C Software and Document License
    url: http://www.w3.org/Consortium/Legal/copyright-software.
  contact:
    name: GitHub Source Code
    url: https://github.com/w3c-ccg/vc-api
paths:
  /workflows/{name}/start:
    post:
      summary: Start a workflow.
      description:
        Starts a workflow with the given name. Optionally, additional information can be provided to the server in the request body that can help it fine tune what information to request from the client in order to continue with the workflow.
      requestBody:
        description: Optional and arbitrary POST data that the client might provide to the server to help it fine tune what information to request from the client in order to continue with the workflow.
        content:
          application/json:
            schema:
              oneOf:
                - type: object
      responses:
        "201":
          description: A new workflow was successfully created for the client.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WorkflowStartResponse"
        "400":
          description: The workflow request was malformed.
        "500":
          description: Internal Error
        "501":
          description: Not implemented
  /workflows/{id}/presentations:
    post:
      summary: Present information to an active workflow.
      operationId: storePresentation
      description: "Delivery endpoint for a client-holder to provide a presentation in compliance with the Verifiable Presentation Request provided in the Notification call. This server-holder MUST match the 'domain' and 'challenge' to a 'domain' and 'challenge' previously sent in a Notification Response, and not already received. The server-holder MUST verify the Presentation. The server MUST store the Presentation if verification passes."
      requestBody:
        description: Details the client provides to the server to help it decide if the presentation should be made.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VerifiablePresentation"
      responses:
        "200":
          description: Presentation was successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VerifiablePresentation"
        "201":
          description: Presentation was received and a new workflow was successfully created for the client.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WorkflowStartResponse"
        "400":
          description: Presentation is malformed
        "501":
          description: Not Implemented
        "500":
          description: Internal Server Error
components:
  schemas:
    WorkflowStartResponse:
      $ref: "./components/WorkflowStartResponse.yml#/components/schemas/WorkflowStartResponse"
    VerifiablePresentation:
      $ref: "./components/VerifiablePresentation.yml#/components/schemas/VerifiablePresentation"
