openapi: 3.0.0
info:
  version: "0.0.3-unstable"
  title: VC API
  description: This is an Experimental Open API Specification for the [VC Data Model](https://www.w3.org/TR/vc-data-model/).
  license:
    name: W3C Software and Document License
    url: http://www.w3.org/Consortium/Legal/copyright-software.
  contact:
    name: GitHub Source Code
    url: https://github.com/w3c-ccg/vc-api
paths:
components:
  schemas:
    Credential:
      type: object
      description: A JSON-LD Verifiable Credential without a proof.
      properties:
        "@context":
          type: array
          description: The JSON-LD context of the credential.
          items:
            type: string
        "id":
          type: string
          description: The ID of the credential. This property MAY be empty. The issuer SHOULD NOT auto-generate the id property if not provided, as a Verifiable Credential does not require the id property to be valid, and there are use cases for which the id property cannot be set.
        "type":
          type: array
          description: The JSON-LD type of the credential.
          items:
            type: string
        "issuer":
          $ref: "./Issuer.yml#/components/schemas/Issuer"
        "issuanceDate":
          type: string
          description: The issuanceDate
        "expirationDate":
          type: string
          description: The expirationDate
        "credentialSubject":
          type: object
          description: A REQUIRED property describing the subject of the credential.
      example:
        {
          "@context":
            [
              "https://www.w3.org/ns/credentials/v2",
              "https://www.w3.org/ns/credentials/examples/v2",
            ],
          "id": "http://example.gov/credentials/3732",
          "type": ["VerifiableCredential", "UniversityDegreeCredential"],
          "issuer": "did:example:123",
          "validFrom": "2020-03-16T22:37:26.544Z",
          "credentialSubject":
            {
              "id": "did:example:123",
              "degree":
                {
                  "type": "BachelorDegree",
                  "name": "Bachelor of Science and Arts",
                }
            }
        }
    UnsecuredCredential:
      type: object
      description: A W3C Verifiable Credential intended for issuance.
      properties:
        "@context":
          type: array
          description: The JSON-LD context of the credential.
          items:
            type: string
        "id":
          type: string
          description: The ID of the credential.
        "type":
          type: array
          description: The JSON-LD type of the credential.
          items:
            type: string
        "issuer":
          $ref: "./Issuer.yml#/components/schemas/IssuerRequest"
        "validFrom":
          type: string
          description: The validFrom date
        "validUntil":
          type: string
          description: The validUntil date
        "credentialSubject":
          type: object
          description: A REQUIRED property describing the subject of the credential.
        "proof":
          type: object
          description: >
            An optional proof or array of proofs for credentials that are secured using proof sets or chains.
            When present, the configuration of the issuer instance determines how these existing proofs are
            processed (e.g., append to create proof sets/chains, or trigger an error).
          oneOf:
            - type: object
            - type: array
              items:
                type: object
      example:
        {
          "@context":
            [
              "https://www.w3.org/ns/credentials/v2",
              "https://www.w3.org/ns/credentials/examples/v2",
            ],
          "id": "http://example.gov/credentials/3732",
          "type": ["VerifiableCredential", "UniversityDegreeCredential"],
          "issuer": "did:example:123",
          "validFrom": "2020-03-16T22:37:26.544Z",
          "credentialSubject":
            {
              "id": "did:example:123",
              "degree":
                {
                  "type": "BachelorDegree",
                  "name": "Bachelor of Science and Arts",
                }
            }
        }
