openapi: 3.0.0
info:
  version: "0.0.3-unstable"
  title: VC API
  description: This is an Experimental Open API Specification for the [VC Data Model](https://www.w3.org/TR/vc-data-model/).
  license:
    name: W3C Software and Document License
    url: http://www.w3.org/Consortium/Legal/copyright-software.
  contact:
    name: GitHub Source Code
    url: https://github.com/w3c-ccg/vc-api
paths:
components:
  schemas:
    Issuer:
      type: object
      description: A JSON-LD Verifiable Credential Issuer.
      oneOf:
        - type: string
        - type: object
          properties:
            id:
              type: string
              description: The issuer id.
      example:
        { "id": "did:key:z6MkjRagNiMu91DduvCvgEsqLZDVzrJzFrwahc4tXLt9DoHd" }
    IssuerRequest:
      type: object
      description: A JSON-LD Verifiable Credential Issuer. The presence of object 'issuer' is optional (SHOULD be omitted). If provided, it MUST adhere to the configuration requirements of the particular implementation. Implementations MUST be able to understand and process the supplied value in accordance with their configuration. In scenarios where multiple configurations exist for a specific endpoint, the 'issuer' object, if present, MAY be utilized to select among multiple potential issuers. In such cases, the provided 'issuer' value MUST align with the available configurations, allowing the implementation to appropriately determine the issuer for the specific endpoint. Implementations MUST ensure that the selected issuer aligns with their configuration and can be processed successfully.
      oneOf:
        - type: string
        - type: object
          properties:
            id:
              type: string
              description: The issuer id.
      example:
        { "id": "did:key:z6MkjRagNiMu91DduvCvgEsqLZDVzrJzFrwahc4tXLt9DoHd" }
