openapi: 3.0.0
info:
  version: "0.0.3-unstable"
  title: VC API
  description: This is an Experimental Open API Specification for the [VC Data Model](https://www.w3.org/TR/vc-data-model/).
  license:
    name: W3C Software and Document License
    url: http://www.w3.org/Consortium/Legal/copyright-software.
  contact:
    name: GitHub Source Code
    url: https://github.com/w3c-ccg/vc-api
paths:
components:
  schemas:
    VerifiablePresentationRequest:
      type: object
      description: A Verifiable Presentation Request.
      properties:
        "query":
          type: array
          description: A set of one or more queries sent by the requester.
          items:
            type: object
            properties:
              "type":
                type: array
                description: The type of the query.
                items:
                  type: string
              "credentialQuery":
                type: object
                description: For QueryByExample queries, specifies the credential request details.
                properties:
                  "reason":
                    type: string
                    description: A human-readable explanation for why the credential is being requested.
                  "example":
                    type: object
                    description: An example of the credential being requested.
                  "acceptedIssuers":
                    type: array
                    description: Accepted issuers for the requested credential.
                    items:
                      type: object
                      properties:
                        "issuer":
                          type: string
                  "acceptedCryptosuites":
                    type: array
                    description: Cryptographic proof suites the verifier will accept. Each element SHOULD be an object with a `cryptosuite` property; however, for backwards compatibility, string values are also accepted and interpreted as the cryptosuite name for a Data Integrity proof.
                    items:
                      oneOf:
                        - type: string
                          description: A cryptosuite name (shorthand for an object with cryptosuite).
                          example: ["eddsa-rdfc-2022", "bbs-2023", "ecdsa-sd-2023"]
                        - type: object
                          properties:
                            "cryptosuite":
                              type: string
                              description: The name of the cryptosuite.
                          example: [{"cryptosuite": "eddsa-rdfc-2022"}, {"cryptosuite": "bbs-2023"}, {"cryptosuite": "ecdsa-sd-2023"}]
                  "acceptedEnvelopes":
                    type: array
                    description: Envelope formats the verifier will accept. Each element SHOULD be an object with a `mediaType` property; however, for backwards compatibility, string values are also accepted and interpreted as the media type for the envelope.
                    items:
                      oneOf:
                        - type: string
                          description: A media type string (shorthand for an object with mediaType).
                          example: ["application/jwt", "application/vc+sd-jwt"]
                        - type: object
                          properties:
                            "mediaType":
                              type: string
                              description: The media type of the envelope format.
                          example: [{"mediaType": "application/jwt"}, {"mediaType": "application/vc+sd-jwt"}]
        "challenge":
          type: string
          description: A challenge, intended to prevent replay attacks, provided by the requester that is typically expected to be included in the Verifiable Presentation response.
        "domain":
          type: string
          description: A domain, intended to prevent replay attacks, provided by the requester that is typically expected to be included in the Verifiable Presentation response.
          items:
            type: string
        "interact":
          type: array
          description: A list of interaction mechanisms that are supported by the server.
          items:
            type: object
            properties:
              "service":
                type: object
                description: A service that is supported by the server that is capable of receiving a response to the Verifiable Presentation Request.
                properties:
                  "type":
                    type: array
                    description: The type of the service.
                    items:
                      type: string
                  "serviceEndpoint":
                    type: string
                    description: A URL that can be utilized for interacting with the service for the purposes of responding to the Verifiable Presentation Request.
      example:
        {
          "query": [{
            "type": "DIDAuthentication"
          }, {
            "type": "QueryByExample",
            "credentialQuery": {
              "reason": "We need to see your existing University Degree credential.",
              "example": {
                "@context": [
                  "https://www.w3.org/2018/credentials/v1",
                  "https://www.w3.org/2018/credentials/examples/v1"
                ],
                "type": "UniversityDegreeCredential"
              },
              "acceptedCryptosuites": [
                {"cryptosuite": "eddsa-rdfc-2022"},
                {"cryptosuite": "ecdsa-rdfc-2019"},
                {"cryptosuite": "bbs-2023"}
              ],
              "acceptedEnvelopes": [
                {"mediaType": "application/jwt"}
              ]
            }
          }],
          "challenge": "3182bdea-63d9-11ea-b6de-3b7c1404d57f",
          "domain": "edu.example",
          "interact": {
            "service": [{
              "type": "UnmediatedPresentationService2021",
              "serviceEndpoint": "https://edu.example/workflows/123456/presentations"
            }]
          }
        }
