openapi: 3.0.0
info:
  version: "0.0.3-unstable"
  title: VC API
  description: This is an Experimental Open API Specification for the [VC Data Model](https://www.w3.org/TR/vc-data-model/).
  license:
    name: W3C Software and Document License
    url: http://www.w3.org/Consortium/Legal/copyright-software.
  contact:
    name: GitHub Source Code
    url: https://github.com/w3c-ccg/vc-api
paths:
components:
  schemas:
    VerifyPresentationOptions:
      type: object
      additionalProperties: false
      description: Options for specifying how a presentation is verified
      properties:
        challenge:
          type: string
          description: A challenge provided by the requesting party of the proof. For example 6e62f66e-67de-11eb-b490-ef3eeefa55f2
        domain:
          type: string
          description: The intended domain of validity for the proof. For example website.example
        returnCredential:
          type: boolean
          description:
            Should the verified credential be returned in the response?
            If true, then the verified credential should be returned in the form in which it was verified.
            If false or not provided, then the verified credential should not be returned.
      example:
        {
          "domain": "example.com",
          "challenge": "d436f0c8-fbd9-4e48-bbb2-55fc5d0920a8",
          "returnCredential": true
        }
