openapi: 3.0.0
info:
  version: "0.0.3-unstable"
  title: VC API
  description: This is an Experimental Open API Specification for the [VC Data Model](https://www.w3.org/TR/vc-data-model/).
  license:
    name: W3C Software and Document License
    url: http://www.w3.org/Consortium/Legal/copyright-software.
  contact:
    name: GitHub Source Code
    url: https://github.com/w3c-ccg/vc-api
paths:
components:
  schemas:
    VerificationResult:
      type: object
      additionalProperties: false
      description: Object to report the result of a verification process on a VerifiablePresentation.
      properties:
        verified:
          type: boolean
          description: Overall verification assertion of the VerifiablePresentation. This is set to 
            <code>true</code> if the VerifiablePresentation and all checked VerifiableCredentials 
            passed verification; otherwise, <code>false</code>. See error handling section for more 
            guidance around errors and warnings, and validation and verification steps.
        verifiablePresentation:
          type: object
          description: The VerifiablePresentation used as the verification input.
        problemDetails:
          type: array
          description: Array consisting of ProblemDetails objects for overall presentation-level issues.
          items:
            $ref: "./ProblemDetails.yml#/components/schemas/ProblemDetails"
        results:
          type: object
          additionalProperties: false
          description: Detailed verification results for both VerifiablePresentation and all 
            VerifiableCredentials contained within it, by default. Keys are mapped to properties 
            from the Verifiable Credential Data Model which are subject to validations.
          properties:
            presentation:
              type: object
              additionalProperties: false
              description: Verification results specific to the VerifiablePresentation itself 
                (not its contained VerifiableCredentials).
              properties:
                challenge:
                  type: object
                  description: If provided in the verification options, the result of validating 
                    the security challenge across all proofs provided.
                  properties:
                    valid:
                      type: boolean
                      description: Result of validating the security challenge across all proofs provided.
                    input:
                      type: string
                      description: The challenge input string.
                domain:
                  type: object
                  description: If provided in the verification options, the result of validating the 
                    security domain across all proofs provided.
                  properties:
                    valid:
                      type: boolean
                      description: Result of validating the security domain across all proofs provided.
                    input:
                      type: string
                      description: The security domain input string.
                holder:
                  type: object
                  description: Result from validating the holder, if any.
                  properties:
                    valid:
                      type: boolean
                      description: Result of validating the holder.
                    input:
                      type: string
                      description: The holder input string.
                proof:
                  type: array
                  description: Results from validating the proof objects if any.
                  items:
                    type: object
                    description: Results from validating a proof object.
                    properties:
                      valid:
                        type: boolean
                        description: Results of validating the proof object.
                      input:
                        type: object
                        description: The proof object.
                      problemDetails:
                        type: array
                        description: Issues sepecific to this proof.
                        items:
                          $ref: "./ProblemDetails.yml#/components/schemas/ProblemDetails"
            credentials:
              type: object
              description: Verification results for the VerifiableCredentials contained in the VerifiablePresentation.
              additionalProperties: false
              properties:
                summary:
                  type: object
                  description: Summary counts providing a quick overview of VerifiableCredential verification results.
                  additionalProperties: false
                  properties:
                    totalCount:
                      type: integer
                      description: Total number of VerifiableCredentials in the VerifiablePresentation.
                    checkedCount:
                      type: integer
                      description: Number of VerifiableCredentials that were actually verified.
                    skippedCount:
                      type: integer
                      description: Number of VerifiableCredentials that were skipped due to options or configuration.
                    passedCount:
                      type: integer
                      description: Number of checked VerifiableCredentials that passed verification.
                    failedCount:
                      type: integer
                      description: Number of checked VerifiableCredentials that failed verification.
                results:
                  type: array
                  description: Detailed verification results for each VerifiableCredential in the 
                    VerifiablePresentation, in the same order as they appear in the verifiableCredential array.
                  items:
                    type: object
                    description: Verification results for a single VerifiableCredential.
                    additionalProperties: false
                    properties:
                      index:
                        type: integer
                        description: Index of this VerifiableCredential in the VerifiablePresentation's 
                          verifiableCredential array.
                      wasChecked:
                        type: boolean
                        description: Whether this VerifiableCredential was actually verified. If false, 
                          detailed verification properties will not be present.
                      verified:
                        type: boolean
                        description: Whether this specific VerifiableCredential pass verification. 
                          Only meaningful if <code>wasChecked</code> is <code>true</code>.
                      skipReason:
                        type: boolean
                        description: Explanation of why verification was skipped for this VerifiableCredential. 
                          Only present if <code>wasChecked</code> is <code>false</code>.
                      validFrom:
                        type: object
                        description: Results of validating the validFrom property, if present in the 
                          verifiableCredential. Only present if <code>wasChecked</code> is <code>true</code>.
                        properties:
                          valid:
                            type: boolean
                            description: Validation result.
                          input:
                            type: string
                            description: The validFrom value.
                      validUntil:
                        type: object
                        description: Results of validating the validUntil property, if present in the 
                          verifiableCredential. Only present if <code>wasChecked</code> is <code>true</code>.
                        properties:
                          valid:
                            type: boolean
                            description: Validation result.
                          input:
                            type: string
                            description: The validUntil value.
                      credentialSchema:
                        type: array
                        description: Results from validating the credentialSchema objects if any. 
                          Only present <code>wasChecked</code> is <code>true</code>.
                        items:
                          type: object
                          description: Results from validating a credentialSchema object.
                          properties:
                            valid:
                              type: boolean
                              description: Results of validating the credentialSchema object.
                            input:
                              type: string
                              description: The credentialSchema object.
                      credentialStatus:
                        type: array
                        description: Results from validating the credentialStatus objects if any. 
                          Only present if <code>wasChecked</code> is <code>true</code>.
                        items:
                          type: object
                          description: Results of validating a credentialStatus object.
                          properties:
                            value:
                              type: integer
                              description: Value of the statusEntry Bit.
                            valid:
                              type: boolean
                              description: Results of validating the credentialStatus object.
                            input:
                              type: object
                              description: The credentialStatus object.
                      proof:
                        type: array
                        description: Results from validating the proof objects if any. 
                          Only present if <code>wasChecked</code> is <code>true</code>.
                        items:
                          type: object
                          description: Results of validating a proof object.
                          properties:
                            valid:
                              type: boolean
                              description: Results of validating the proof object.
                            input:
                              type: object
                              description: The proof object.
                            problemDetails:
                              type: array
                              description: Issues specific to this proof.
                              items:
                                $ref: "./ProblemDetails.yml#/components/schemas/ProblemDetails"
                      problemDetails:
                        type: array
                        description: Issues specific to this individual VerifiableCredential, present regardless of <code>wasChecked</code> status.
                        items:
                          $ref: "./ProblemDetails.yml#/components/schemas/ProblemDetails"
      example: {
        "verified": false,
        "verifiablePresentation": {},
        "problemDetails": [
          {
            "type": "https://www.w3.org/TR/vc-data-model-2.0/#PARSING_ERROR",
            "title": "Parsing error",
            "description": "There was a parsing error on line 32, column 5: A comma was expected after the \" character."
          }
        ],
        "results": {
          "presentation": {
            "challenge": {
              "valid": true,
              "input": "d436f0c8-fbd9-4e48-bbb2-55fc5d0920a8"
            },
            "domain": {
              "valid": true,
              "input": "example.com"
            },
            "holder": {
              "valid": true,
              "input": "did:example:123"
            },
            "proof": [{
              "valid": true,
              "input": {
                "type": "DataIntegrityProof",
                "cryptosuite": "eddsa-rdfc-2022",
                "created": "2020-04-02T18:28:08Z",
                "verificationMethod": "did:example:123#z6MksHh7qHWvybLg5QTPPdG2DgEjjduBDArV9EF9mRiRzMBN",
                "proofPurpose": "authentication",
                "proofValue": "z5h8W7qJkNrhGjJHWxZ8oN5h8gYZ4h8x7h5b8k2dqKwJ5J8j7h5k8m3qKvJ2j7qJ5h8gYZ4h8x7h5b8k2dqKwJ5J8j7h5k8m3qKvJ2j7qJ5h8gYZ4h8x"
              },
              "problemDetails": []
            }
           ]
          },
          "credentials": {
            "summary": {
              "totalCount": 3,
              "checkedCount": 2,
              "skippedCount": 1,
              "passedCount": 1,
              "failedCount": 1
            },
            results: [
              {
                "index": 0,
                "wasChecked": true,
                "verified": true,
                "validFrom": {
                  "valid": true,
                  "input": "2020-03-16T22:37:26.544Z"
                },
                "validUntil": {
                  "valid": true,
                  "input": "2025-03-16T22:37:26.544Z"
                },
                "credentialStatus": [
                  {
                    "value": 0,
                    "valid": true,
                    "input": {}
                  }
                ],
                "proof": [
                  {
                    "valid": true,
                    "input": {},
                    "problemDetails": []
                  }
                ],
                "problemDetails": []
              },
              {
                "index": 1,
                "wasChecked": true,
                "verified": false,
                "validFrom": {
                  "valid": true,
                  "input": "2020-03-16T22:37:26.544Z"
                },
                "validUntil": {
                  "valid": false,
                  "input": "2022-03-16T22:37:26.544Z"
                },
                "credentialStatus": [
                  {
                    "value": 1,
                    "valid": false,
                    "input": {}
                  }
                ],
                "proof": [
                  {
                    "valid": false,
                    "input": {},
                    "problemDetails": [
                      {
                        "type": "https://www.w3.org/TR/vc-data-model-2.0/#CRYPTOGRAPHIC_SECURITY_ERROR",
                        "title": "Cryptographic security error",
                        "details": "The proof signature verification failed. The signature does not match the expected value for the given verification method."
                      }
                    ]
                  }
                ],
                "problemDetails": [
                  {
                    "type": "https://www.w3.org/TR/vc-data-model-2.0/#CREDENTIAL_EXPIRED",
                    "title": "Credential expired",
                    "details": "The credential's validUntil date of '2022-03-16T22:37:26.544Z' has passed."
                  }
                ]
              },
              {
                "index": 2,
                "wasChecked": false,
                "verified": false,
                "skipReason": "VC verification disabled via options",
                "problemDetails": []
              }
            ],
          }
        }
      }
