openapi: 3.0.0
info:
  version: "0.0.3-unstable"
  title: VC API
  description: This is an Experimental Open API Specification for the [VC Data Model](https://www.w3.org/TR/vc-data-model/).
  license:
    name: W3C Software and Document License
    url: http://www.w3.org/Consortium/Legal/copyright-software.
  contact:
    name: GitHub Source Code
    url: https://github.com/w3c-ccg/vc-api
paths:
components:
  schemas:
    VerificationResult:
      type: object
      additionalProperties: false
      description: Object summarizing a verification
      properties:
        verified:
          type: bool
          description: Overall verification assertion of the payload. This is set to True if no errors were detected during the verification process, otherwise False. See error handling section for more guidance around errors, warnings, validation and verification.
        results:
          type: object
          additionalProperties: false
          description: Verification results to be included as a more verbose output.
          properties:
            validityPeriod:
              type: object
              description: Results from validating the validFrom and validUntil values if present in the VerifiableCredential.
              properties:
                valid:
                  type: bool
                  description: Results from validating the validFrom and validUntil values. 
                validFrom:
                  type: string
                  description: The validFrom value.
                validUntil:
                  type: string
                  description: The validUntil value.
            credentialSchema:
              type: array
              description: Results from validating the credentialSchema objects if any.
              items:
                type: object
                description: Results from validating a credentialSchema object.
                properties:
                  valid:
                    type: bool
                    description: Results from validating the credentialSchema object.
                  input:
                    type: object
                    description: The credentialSchema object.
            credentialStatus:
              type: array
              description: Results from validating the credentialStatus objects if any.
              items:
                type: object
                description: Results from validating a credentialStatus object.
                properties:
                  valid:
                    type: bool
                    description: Results from validating the credentialStatus object.
                  input:
                    type: object
                    description: The credentialStatus object.
            proof:
              type: array
              description: Results from validating the proof objects if any.
              items:
                type: object
                description: Results from validating a proof object.
                properties:
                  valid:
                    type: bool
                    description: Results from validating the proof object.
                  input:
                    type: object
                    description: The proof object.
        warnings:
          type: array
          description: Array consisting of ProblemDetails warning objects.
          items:
            type: object
        errors:
          type: array
          description: Array consisting of ProblemDetails error objects.
          items:
            type: object
        credential:
          type: object
          description: The verified credential used as the verification payload.
      example: { "verified": True, "results": {"credentialSchema": [], "credentialStatus": [], "proof": []}, "warnings": [], "errors": [] }
