openapi: 3.0.0
info:
  version: "0.0.3-unstable"
  title: VC HTTP API
  description: This is an Experimental Open API Specification for the [VC Data Model](https://www.w3.org/TR/vc-data-model/).
  license:
    name: W3C Software and Document License
    url: http://www.w3.org/Consortium/Legal/copyright-software.
  contact:
    name: GitHub Source Code
    url: https://github.com/w3c-ccg/vc-api
paths:
components:
  schemas:
    WorkflowStartResponse:
      type: object
      description: A response to a request to start a workflow.
      properties:
        verifiablePresentationRequest:
          $ref: "#/components/schemas/VerifiablePresentationRequest"
      example:
        {
          "verifiablePresentationRequest": {
            "query": [{
              "type": "DIDAuth"
            }, {
              "type": "QueryByExample",
              "credentialQuery": {
                "reason": "We need to see your existing University Degree credential.",
                "example": {
                  "@context": [
                    "https://www.w3.org/2018/credentials/v1",
                    "https://www.w3.org/2018/credentials/examples/v1"
                  ],
                  "type": "UniversityDegreeCredential"
                }
              }
            }],
            "challenge": "3182bdea-63d9-11ea-b6de-3b7c1404d57f",
            "domain": "edu.example",
            "interact": {
              "service": [{
                "type": "UnmediatedPresentationService2021",
                "serviceEndpoint": "https://edu.example/workflows/123456/presentations"
              }]
            }
          }
        }
    VerifiablePresentationRequest:
      $ref: "./VerifiablePresentationRequest.yml#/components/schemas/VerifiablePresentationRequest"
